version: '3'

services:
  db:
    image: mysql:8.0.23
    container_name: execice01
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql